# Day 1: TF.Basics


## 1 Quickstart for Beginners

1. Load a prebuild dataset
2. Build neural network that classifies images
3. Train neural network
4. Evaluat accuracy of model

In [1]:
#Setup
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.2


In [3]:
# 1 Load dataset
minst = tf.keras.datasets.mnist #load dataset of 70.000 handwriting digits for image classification
(x_train, y_train), (x_test, y_test) = minst.load_data() #split dataset x = images, y = image labels
x_train, x_test = x_train / 255.0, x_test / 255.0 #normalize dataset

In [4]:
# 2 Build machine learning model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
# 3 For each example, the model returns a vector of logits or log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.29410344, -0.09365064,  0.9759016 ,  0.00978383, -0.04661554,
         1.431026  ,  0.32465655,  0.65307313,  0.8410043 , -0.40913546]],
      dtype=float32)

In [7]:
# 4 The tf.nn.softmax function converts these logits to probabilities for each class
tf.nn.softmax(predictions).numpy()

array([[0.0773832 , 0.05251063, 0.15301989, 0.05823288, 0.05503948,
        0.24121587, 0.07978398, 0.1108014 , 0.13370964, 0.0383031 ]],
      dtype=float32)

In [9]:
# 5 Define a loss function for training using losses.SparseCategoricalCrossentropy,
# which takes a vector of logits and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
# 6 This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.
# This untrained model gives probabilities close to random (1/10 for each class), 
# so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.
loss_fn(y_train[:1], predictions).numpy()

1.422063

In [11]:
# 7 Configure and compile the model 
model.compile(optimizer="adam",
              loss=loss_fn,
              metrics=["accuracy"])

### Train and evaluate the model


In [12]:
# 1 Adjust model parameters and minimize loss
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3034 - accuracy: 0.9116
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1470 - accuracy: 0.9569
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1100 - accuracy: 0.9663
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0898 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0766 - accuracy: 0.9765


In [14]:
# 2 Check the model performance 
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0783 - accuracy: 0.9757 - 1s/epoch - 3ms/step


[0.07831104844808578, 0.9757000207901001]

In [ ]:
# => Image classifier accuracy ~98% on this dataset

In [16]:
# 3 Return probability of the matching for a specific test
probability_model = tf.keras.Sequential([
    model, 
    tf.keras.layers.Softmax()
])

In [31]:
results = probability_model(x_test[:5])
results

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1503395e-07, 1.1126826e-09, 3.8326502e-06, 9.5771858e-05,
        4.8855554e-13, 3.4273594e-07, 9.8923819e-14, 9.9989820e-01,
        2.8330686e-07, 1.4797010e-06],
       [1.3605890e-07, 9.3408798e-06, 9.9998081e-01, 8.9035975e-06,
        3.4261591e-18, 8.6251822e-07, 9.2640340e-10, 6.4970253e-17,
        4.8001656e-09, 5.0358646e-14],
       [3.0703680e-07, 9.9938560e-01, 7.5985823e-05, 8.8133456e-06,
        2.1890783e-05, 9.8765513e-06, 1.4524404e-05, 4.1319238e-04,
        6.9637063e-05, 1.6551377e-07],
       [9.9996722e-01, 2.7274790e-11, 4.5079505e-06, 5.6066940e-10,
        1.2552370e-07, 8.0642437e-08, 2.2189672e-05, 1.4946579e-07,
        4.2425604e-08, 5.7167422e-06],
       [5.5000521e-07, 4.3841930e-10, 7.1312356e-06, 2.6230421e-08,
        9.9786085e-01, 3.8091167e-07, 3.0576236e-06, 5.2275165e-05,
        1.0644796e-06, 2.0745751e-03]], dtype=float32)>

In [35]:
rounded_resultst = tf.math.round(results)
rounded_resultst

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

In [37]:
#Suggestion for results = [7, 2, 1, 0, 4]
# How to show the results in numbers automatically?
# How to compare the results?

## 2 Exercise

In [26]:
from tensorflow import keras 
import numpy as np

In [23]:
# 1 Define and compile neural network
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])]) # 1 layer / 1 neuron

In [25]:
# 2 Compile NN with 2 functions: Loss and optimizer
model.compile(optimizer="sgd", loss="mean_squared_error")

In [27]:
# 3 Providing data
xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

In [29]:
# 4 Training NN
model.fit(xs, ys, epochs=500)
print(model.predict([10.0]))

Epoch 1/500
1/1 [==============================] - 0s 214ms/step - loss: 15.5985
Epoch 2/500
1/1 [==============================] - 0s 7ms/step - loss: 12.5156
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 10.0851
Epoch 4/500
1/1 [==============================] - 0s 8ms/step - loss: 8.1681
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 6.6550
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 5.4599
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 4.5151
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 3.7672
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 3.1744
Epoch 10/500
1/1 [==============================] - 0s 5ms/step - loss: 2.7037
Epoch 11/500
1/1 [==============================] - 0s 7ms/step - loss: 2.3291
Epoch 12/500
1/1 [==============================] - 0s 12ms/step - loss: 2.0303
Epoch 13/500
1/1 [==============================] - 0s 

## 3 Exercise

In this exercise you'll try to build a neural network that predicts the price of a house according to a simple formula.

So, imagine if house pricing was as easy as a house costs 50k + 50k per bedroom, so that a 1 bedroom house costs 100k, a 2 bedroom house costs 150k etc.

How would you create a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.

Hint: Your network might work better if you scale the house price down. You don't have to give the answer 400...it might be better to create something that predicts the number 4, and then your answer is in the 'hundreds of thousands' etc.

In [48]:
# GRADED FUNCTION: house_model
def house_model(y_new):
    x = np.array([1.0, 2.0, 3.0, 4.0, 5.0 , 6.0], dtype=float)
    y = np.array([100.0, 150.0, 200.0, 250.0, 300.0, 350.0], dtype=float)
    model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
    model.compile(optimizer="SGD", loss="mse")
    model.fit(x,y, epochs=500)
    return model.predict(y_new)[0]

In [49]:
prediction = house_model([7])
print(prediction)

Epoch 1/500
1/1 [==============================] - 0s 336ms/step - loss: 57162.1562
Epoch 2/500
1/1 [==============================] - 0s 17ms/step - loss: 26591.6719
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 12441.7471
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 5891.7578
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 2859.2546
Epoch 6/500
1/1 [==============================] - 0s 6ms/step - loss: 1454.7577
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 803.7556
Epoch 8/500
1/1 [==============================] - 0s 6ms/step - loss: 501.5027
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 360.6673
Epoch 10/500
1/1 [==============================] - 0s 12ms/step - loss: 294.5478
Epoch 11/500
1/1 [==============================] - 0s 12ms/step - loss: 263.0161
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 247.4992
Epoch 13/500
1/1 [=====

# Day 2: TF.ComputerVision (CV)

#Day 3: TF.Natrual Language Processing (NLP)

#Day 4: TF.Time Series Forcasting